/*
 * Btrieve DOS Emulation driver common routines
 *
 * (C) leecher@dose.0wnz.at   05/2019
 *
 */

#include "btrfnc.h"

BTI_WORD OperationFlags[100] =
{
  OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_READ_POSBLOCK,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_READ_POSBLOCK,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN,
  OP_READ_KEYBUFFER | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_KEYBUFFER | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_INVALID,
  OP_READ_KEYBUFFER,
  OP_RETN_KEYBUFFER | OP_READ_KEYNUMBER,
  0,
  0,
  0,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN,
  0,
  OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN,
  OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_READ_KEYBUFFER | OP_READ_KEYNUMBER,
  OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_READ_POSBLOCK,
  OP_READ_POSBLOCK | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  0,
  0,
  OP_RETN_INVALID,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_POSBLOCK | OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_POSBLOCK | OP_READ_POSBLOCK,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_INVALID,
  OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_KEYBUFFER | OP_RETN_POSBLOCK | OP_READ_POSBLOCK | OP_READ_KEYNUMBER,
  OP_RETN_POSBLOCK | OP_READ_KEYBUFFER | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_BUFLEN | OP_RETN_DATABUFFER | OP_READ_POSBLOCK | OP_READ_KEYNUMBER | OP_READ_BUFLEN | OP_READ_DATABUFFER,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_READ_KEYBUFFER | OP_READ_KEYNUMBER,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID,
  OP_RETN_INVALID
};

fpBTRCALL BTRCALL;
fpBTRCALLID BTRCALLID;

BTI_WORD BtrQueryOps(BTI_WORD op)
{
    if (op >= 0) return OperationFlags[op % 100];
    return OP_RETN_INVALID;
}

BTI_WORD CopyBackParams(BTI_WORD opFlag, XDATA *pXdata, BTI_WORD btrRet, BTI_BUFFER_PTR posBlockPtr)
{
    BTI_WORD op; 
    BTI_BOOL bRetParams = FALSE;

    op = pXdata->FUNCTION % 100;
    /*  Add 50 (32h) to any "get" operation to just return the key data.  */
    if (op >= 50+B_GET_EQUAL && op != 50+B_STAT || op == 50+B_INSERT)
        op -= 50;

    switch (btrRet)
    {
    case B_NO_ERROR:
    case B_REJECT_COUNT_REACHED:
    case B_OPTIMIZE_LIMIT_REACHED:
    case B_INVALID_EXTRACTOR:
    case B_DATA_MESSAGE_TOO_SMALL:
    case B_CHUNK_OFFSET_TOO_LONG:
        bRetParams = TRUE;
        break;
    case B_END_OF_FILE:
        if (op >= B_GET_NEXT_EXTENDED) bRetParams = 1;
        break;
    case B_RECORD_INUSE:
        bRetParams = op == B_GET_NEXT_EXTENDED || op == B_GET_PREV_EXTENDED || op == B_STEP_NEXT_EXT || B_STEP_PREVIOUS_EXT;
        break;
    case B_VARIABLE_PAGE_ERROR:
    case B_DATALENGTH_ERROR:
        bRetParams = pXdata->XFACE_ID == VARIABLE_ID;
        break;

    }
    if (op == B_EXT_INSERT) bRetParams = TRUE;
    if ((op == B_INSERT || op == B_UPDATE || op == B_EXT_INSERT) &&
        (btrRet == B_DATA_MESSAGE_TOO_SMALL || btrRet == B_DATALENGTH_ERROR &&
            pXdata->BUF_LEN < *(BTI_WORD*)posBlockPtr))
        bRetParams = FALSE;
    if (!bRetParams) opFlag = ~OP_RETN_MASK;

    return opFlag;
}

